version: 2
sphinx:
  configuration: docs/src/conf.py
formats:
  - pdf
  - epub
python:
  # NOTE: Keep version in sync with gh-actions
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: core
    - method: pip
      path: cli
    - method: pip
      path: lib
    - method: pip
      path: exec
    - method: pip
      path: devtools
    - method: pip
      path: audio
