# "Template" workflow that can be called by other workflows as well as manually triggered
# https://docs.github.com/en/actions/learn-github-actions/reusing-workflows

name: Build & Upload to Prod PyPI

on:
  workflow_call:  # allows calls from other workflows
    inputs:
      package-dir:
        description: "Directory of package to build & upload"
        required: true
        type: string
      package-name:
        description: "Import name of package (e.g. klio_core, not klio-core)"
        required: true
        type: string
  workflow_dispatch:  # manual trigger
    inputs:
      package-dir:
        description: "Directory of package to build & upload"
        required: true
        type: string
      package-name:
        description: "Import name of package (e.g. klio_core, not klio-core)"
        required: true
        type: string

jobs:
  build_install:
    name: "Build & Install ${{ inputs.package-name }}"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: "Set up Python 3.8"
        uses: "actions/setup-python@v2"
        with:
          python-version: 3.8

      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m pip install build virtualenv twine --user

      - name: "${{ inputs.package-name }}: Build wheel & sdist"
        run: |
          set -xe
          pwd
          python -VV
          python -m build --sdist --wheel --outdir ${{ inputs.package-dir }}/dist/ ${{ inputs.package-dir }}/

      - name: "${{ inputs.package-name }}: Check Long Description"
        run: |
          set -xe
          python -VV
          python -m twine check ${{ inputs.package-dir }}/dist/*

      - name: "${{ inputs.package-name }}: Test sdist installation from local build"
        run: |
          set -xe
          python -VV
          python -m virtualenv sdist-test
          source sdist-test/bin/activate
          python -m pip install ${{ inputs.package-dir }}/dist/*.tar.gz
          python -c 'import ${{ inputs.package-name }}; print(${{ inputs.package-name }}.__version__)'
          deactivate

      - name: "${{ inputs.package-name }}: Test wheel installation from local build"
        run: |
          set -xe
          python -VV
          python -m virtualenv wheel-test
          source wheel-test/bin/activate
          python -m pip install ${{ inputs.package-dir }}/dist/*.whl
          python -c 'import ${{ inputs.package-name }}; print(${{ inputs.package-name }}.__version__)'
          deactivate

      # Upload artifact so it can be downloaded & used in the following job
      - name: "Archive artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: dist-${{ inputs.package-name }}
          path: ${{ inputs.package-dir }}/dist/*
          retention-days: 1

  upload_prod_pypi:
    name: "Upload ${{ inputs.package-name }} to PyPI Prod Server"
    needs: build_install
    outputs:
      version: ${{ steps.version.outputs.version }}
    runs-on: "ubuntu-latest"
    steps:
      - name: "Download ${{ inputs.package-name }} artifacts from GH"
        id: download
        uses: actions/download-artifact@v2
        with:
          name: dist-${{ inputs.package-name }}

      # Save the version as a variable we can use later when we test
      # the installation
      - name: "Grab Package Version for ${{ inputs.package-name }}"
        id: version
        shell: bash
        run: |
          set -xe
          FULL_PATH=$(ls ${{ steps.download.outputs.download-path }}/*.whl)
          BASE_NAME=$(basename ${FULL_PATH} .whl)
          VERSION=$(echo ${BASE_NAME} | cut -d- -f2)
          echo ::set-output name=version::$(echo ${VERSION})

      - name: "Upload ${{ inputs.package-name }} artifacts to Prod PyPI"
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PROD_PYPI_API_TOKEN }}
          verbose: true
          packages_dir: ${{ steps.download.outputs.download-path }}

  install_prod_pypi:
    name: "Test installation of ${{ inputs.package-name }} from Prod PyPI"
    needs: upload_prod_pypi
    runs-on: "ubuntu-latest"
    steps:
      - name: Set up Python 3.8
        uses: "actions/setup-python@v2"
        with:
          python-version: 3.8

      - name: "Sleep to wait for propagation"
        run: |
          set -xe
          sleep 120

      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m pip install virtualenv --user

      - name: "Test wheel install of ${{ inputs.package-name }} from Prod PyPI"
        run: |
          set -xe
          python -m virtualenv prod-pypi-wheel
          source prod-pypi-wheel/bin/activate
          python -m pip install -i https://pypi.org/simple --only-binary=${{ inputs.package-name }} ${{ inputs.package-name }}==${{ needs.upload_prod_pypi.outputs.version }}
          python -c 'import ${{ inputs.package-name }}; assert ${{ inputs.package-name }}.__version__ == "${{ needs.upload_prod_pypi.outputs.version }}"'
          deactivate

      - name: "Test sdist install of ${{ inputs.package-name }} from Prod PyPI"
        run: |
          set -xe
          python -m virtualenv prod-pypi-sdist
          source prod-pypi-sdist/bin/activate
          python -m pip install -i https://pypi.org/simple --no-binary=${{ inputs.package-name }} ${{ inputs.package-name }}==${{ needs.upload_prod_pypi.outputs.version }}
          python -c 'import ${{ inputs.package-name }}; assert ${{ inputs.package-name }}.__version__ == "${{ needs.upload_prod_pypi.outputs.version }}"'
          deactivate
