name: Build & Release to PyPI

on:
  # TODO: testing with manual triggering first - will update to trigger on push
  # for certain branches/tags/whatever is decided once we confirm this works
  workflow_dispatch:  # manual trigger
    inputs:
      package-dir:
        description: "Directory of package to build & upload"
        required: true
        type: string
      package-name:
        description: "Import name of package to build & upload (e.g. klio_core, not klio-core)"
        required: true
        type: string

jobs:
  # core needs to be released first since other klio packages depend on it
  release_core:
    name: "[core] Build & Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build wheel & sdist"
        uses: spotify/klio/.github/workflows/build.yml@develop
        with:
          package-dir: core
          package-name: klio_core
      - name: "Upload to Test PyPI"
        uses: spotify/klio/.github/workflows/upload_test.yml@develop
        with:
          package-name: klio_core
      - name: "Upload to Prod PyPI"
        uses: spotify/klio/.github/workflows/upload_test.yml@develop
        with:
          package-name: klio_core

  # lib & cli needs to be released next since exec & devtools depend on it
  release_lib_cli_audio:
    name: "[lib,cli,audio] Build & Release"
    needs: release_core
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        include:
          - package-dir: lib
            package-name: klio
          - package-dir: cli
            package-name: klio_cli
          - package-dir: audio
            package-name: klio_audio            
    steps:
      - name: "[${{ matrix.package-name }}] Build wheel & sdist"
        uses: spotify/klio/.github/workflows/build.yml@develop
        with:
          package-dir: ${{ matrix.package-dir}}
          package-name: ${{ matrix.package-name}}
      - name: "[${{ matrix.package-name }}] Upload to Test PyPI"
        uses: spotify/klio/.github/workflows/upload_test.yml@develop
        with:
          package-name: ${{ matrix.package-name}}
      - name: "[${{ matrix.package-name }}] Upload to Prod PyPI"
        uses: spotify/klio/.github/workflows/upload_test.yml@develop
        with:
          package-name: ${{ matrix.package-name}}

  release_exec_devtools:
    name: "[exec,devtools] Build & Release"
    needs: release_lib_cli_audio
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        include:
          - package-dir: exec
            package-name: klio_exec
          - package-dir: devtools
            package-name: klio_devtools
    steps:
      - name: "[${{ matrix.package-name }}] Build wheel & sdist"
        uses: spotify/klio/.github/workflows/build.yml@develop
        with:
          package-dir: ${{ matrix.package-dir}}
          package-name: ${{ matrix.package-name}}
      - name: "[${{ matrix.package-name }}] Upload to Test PyPI"
        uses: spotify/klio/.github/workflows/upload_test.yml@develop
        with:
          package-name: ${{ matrix.package-name}}
      - name: "[${{ matrix.package-name }}] Upload to Prod PyPI"
        uses: spotify/klio/.github/workflows/upload_test.yml@develop
        with:
          package-name: ${{ matrix.package-name}}