# "Template" workflow that can be called by other workflows as well as manually triggered
# https://docs.github.com/en/actions/learn-github-actions/reusing-workflows

name: Upload to Prod PyPI

on:
  workflow_call:  # allows calls from other workflows
    inputs:
      package-name:
        description: "Import name of package to upload (e.g. klio_core, not klio-core)"
        required: true
        type: string
  workflow_dispatch:  # manual trigger
    inputs:
      package-name:
        description: "Import name of package to upload (e.g. klio_core, not klio-core)"
        required: true
        type: string

# Note: this needs the build.yml workflow to run for the desired package first 
# so that the artifact is uploaded to GH temp storage, but since this workflow 
# is a reusable workflow, it can't call another reusable workflow 
# (GH limitations https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#limitations)
jobs:
  upload_prod_pypi:
    name: Upload packages to PyPI Prod Server
    outputs:
      version: ${{ steps.version.outputs.version }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Download ${{ github.event.inputs.package-name }} artifacts from GH
        id: download
        uses: actions/download-artifact@v2
        with:
          name: dist-${{ github.event.inputs.package-name }}

      # Save the version as a variable we can use later when we test
      # the installation
      - name: Grab Package Version
        id: version
        shell: bash
        run: |
          set -xe
          FULL_PATH=$(ls ${{ steps.download.outputs.download-path }}/*.tar.gz)
          BASE_NAME=$(basename ${FULL_PATH} .tar.gz)
          VERSION=$(echo ${BASE_NAME} | cut -d- -f3)
          echo ::set-output name=version::$(echo ${VERSION})

      - name: Upload artifacts to Prod PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PROD_PYPI_API_TOKEN }}
          verbose: true
          packages_dir: ${{ steps.download.outputs.download-path }}

  install_prod_pypi:
    name: Test installation from Prod PyPI
    needs: upload_prod_pypi
    runs-on: "ubuntu-latest"
    steps:
      - name: Set up Python 3.8
        uses: "actions/setup-python@v2"
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          set -xe
          python -VV
          python -m pip install virtualenv --user

      - name: Test wheel install from Prod PyPI
        run: |
          set -xe
          python -m virtualenv prod-pypi-wheel
          source prod-pypi-wheel/bin/activate
          python -m pip install -i https://pypi.org/simple --only-binary=${{ github.event.inputs.package-name }} ${{ github.event.inputs.package-name }}==${{ needs.upload_prod_pypi.outputs.version }}
          python -c 'import ${{ github.event.inputs.package-name }}; assert ${{ github.event.inputs.package-name }}.__version__ == "${{ needs.upload_prod_pypi.outputs.version }}"'
          deactivate

      - name: Test sdist install from Prod PyPI
        run: |
          set -xe
          python -m virtualenv prod-pypi-sdist
          source prod-pypi-sdist/bin/activate
          python -m pip install -i https://pypi.org/simple --no-binary=${{ github.event.inputs.package-name }} ${{ github.event.inputs.package-name }}==${{ needs.upload_prod_pypi.outputs.version }}
          python -c 'import ${{ github.event.inputs.package-name }}; assert ${{ github.event.inputs.package-name }}.__version__ == "${{ needs.upload_prod_pypi.outputs.version }}"'
          deactivate
